DROP ALL OBJECTS;

CREATE TABLE `TB_USUARIO` (
	`ID` INT(9) NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(50) NOT NULL
);
ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `PK_USUARIO` PRIMARY KEY (`ID`);
ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `UQ_USUARIO_NOME` UNIQUE (`NOME`);


CREATE TABLE `TB_FUNCAO` ( 
	`ID` INT(9) NOT NULL AUTO_INCREMENT, 
	`NOME` VARCHAR(50) NOT NULL
);
ALTER TABLE `TB_FUNCAO` ADD CONSTRAINT `PK_FUNCAO` PRIMARY KEY (`ID`);
ALTER TABLE `TB_FUNCAO` ADD CONSTRAINT `UQ_FUNCAO_NOME` UNIQUE (`NOME`);


CREATE TABLE `TB_USUARIO_FUNCAO` ( 
	`USUARIO_ID` INT(9),
	`FUNCAO_ID` INT(9) 
);
ALTER TABLE `TB_USUARIO_FUNCAO` ADD CONSTRAINT `FK_USUARIO_FUNCAO_USUARIO` FOREIGN KEY (`USUARIO_ID`) REFERENCES `TB_USUARIO` (`ID`);
ALTER TABLE `TB_USUARIO_FUNCAO` ADD CONSTRAINT `FK_USUARIO_FUNCAO_FUNCAO`  FOREIGN KEY (`FUNCAO_ID`)  REFERENCES `TB_FUNCAO` (`ID`);