package net.acdcjunior.piloto.domain;

import javax.persistence.*;

import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "tb_usuario") 
public class Usuario {

	@Id // @Id indicates that this it a unique primary key
    @GeneratedValue // @GeneratedValue indicates that value is automatically generated by the server
    private Integer id;

    // the optional @Column allows us makes sure that the name is limited to a suitable size and is unique
	@Column(length = 50, unique = true)
    private String nome;
    
	@ManyToMany
	@JoinTable(name="tb_usuario_funcao", joinColumns={@JoinColumn(name="usuario_id")}, inverseJoinColumns={@JoinColumn(name="funcao_id")})
    private final Set<Funcao> funcoes = new HashSet<Funcao>();

    public void setId(Integer id) { this.id = id; }
    public Integer getId() { return id; }

    public void setNome(String nome) { this.nome = nome; }
    public String getNome() { return nome; }

    public boolean addFuncao(Funcao funcao) { return funcoes.add(funcao); }
    public Set<Funcao> getFuncoes() { return funcoes; }
    
    @Override
    public boolean equals(Object o) {
    	return o != null && o instanceof Usuario && ((Usuario)o).getId() == this.getId();
    }
    @Override
    public int hashCode() {
    	return this.getId();
    }

}